"""
Train a CNN to Detect Supernovae by Comparing JWST and HST PNG Images

APPROACH: Feed raw images (HST, JWST1, JWST2) as 3-channel input.
No subtraction. The CNN learns what a supernova looks like from
verified ground truth data.

TRAINING DATA (verified by visual inspection):
  Ground-truth catalog: data/sn_v03.csv
    Columns: ID, TELESCOPE  (TELESCOPE is "JWST" or "HST")
    Currently 34 confirmed SN (30 JWST, 4 HST).

  IDs 1 through 53131 were inspected exhaustively:
    - SN IDs from the catalog within this range: positive examples
    - ALL other objects in this range: confirmed NOT supernovae
  This gives ~53,000 verified negatives plus the catalog positives in range.

  Additional artificial supernovae are generated by injecting
  Gaussian point sources near the galaxy center.

  All confirmed SN across the full dataset are used as positives.

PHYSICAL CONSTRAINTS:
  - SN appears near the host galaxy (center of PNG)
  - JWST SN appears in both JWST filters
  - HST SN appears only in HST

Expected rate: ~1 per 7,000 objects → ~30 from 212K objects

Usage:
    python train_supernova_cnn.py
    python train_supernova_cnn.py --epochs 50 --num-workers 8
"""

import argparse
import csv
import glob
import os
import re
import sys
import time
import random

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# Default path to the ground-truth supernova catalog (relative to this script).
# CSV columns: ID, TELESCOPE  (TELESCOPE is "JWST" or "HST")
DEFAULT_KNOWN_SN_CSV = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "data", "sn_v03.csv"
)

# Verified-by-visual-inspection ID range: every ID in [1, VERIFIED_MAX_ID]
# was inspected. SN IDs in this range are positives; all others in the range
# are confirmed negatives.
VERIFIED_MAX_ID = 53131


def load_known_supernovae(csv_path):
    """Load confirmed supernovae from CSV.

    Expected columns: ID, TELESCOPE ("JWST" or "HST").
    Returns dict {object_id (str): telescope (str)}.
    """
    known = {}
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            obj_id = (row.get("ID") or "").strip()
            telescope = (row.get("TELESCOPE") or "").strip().upper()
            if obj_id and telescope in ("JWST", "HST"):
                known[obj_id] = telescope
    return known

IMAGE_SIZE = 64
NUM_CHANNELS = 3  # HST, JWST1, JWST2


# ============================================================
# Data loading
# ============================================================

def parse_filename(filename):
    basename = os.path.splitext(filename)[0]
    match = re.match(r"^(.+?)_([^_]+)_(hstcosmos|jwst[12])$", basename)
    if match:
        return match.group(1), match.group(2), match.group(3)
    return None


def build_file_maps(hst_dir, jwst_dir):
    hst_files = sorted(glob.glob(os.path.join(hst_dir, "*.png")))
    jwst_files = sorted(glob.glob(os.path.join(jwst_dir, "*.png")))
    print(f"Found {len(hst_files)} HST files, {len(jwst_files)} JWST files")
    file_map = {}
    for f in hst_files:
        parsed = parse_filename(os.path.basename(f))
        if parsed:
            obj_id = parsed[0]
            if obj_id not in file_map:
                file_map[obj_id] = {}
            file_map[obj_id]["hst"] = f
    for f in jwst_files:
        parsed = parse_filename(os.path.basename(f))
        if parsed:
            obj_id, _, img_type = parsed
            if obj_id not in file_map:
                file_map[obj_id] = {}
            file_map[obj_id][img_type] = f
    return file_map


def load_image(filepath, size=IMAGE_SIZE):
    """Load PNG, resize, normalize to [0, 1]."""
    img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return None
    img = cv2.resize(img, (size, size), interpolation=cv2.INTER_AREA)
    return img.astype(np.float32) / 255.0


def load_triplet(files, size=IMAGE_SIZE):
    """Load HST + JWST1 + JWST2 as 3-channel array."""
    hst = load_image(files["hst"], size)
    jwst1 = load_image(files["jwst1"], size)
    jwst2 = load_image(files["jwst2"], size)
    if hst is None or jwst1 is None or jwst2 is None:
        return None
    return np.stack([hst, jwst1, jwst2], axis=0)


# ============================================================
# Artificial supernova injection
# ============================================================

def inject_supernova_at(image, x, y, peak, sigma):
    """Add Gaussian point source at (x, y)."""
    img = image.copy()
    h, w = img.shape
    yy, xx = np.mgrid[0:h, 0:w]
    gaussian = peak * np.exp(-((xx - x)**2 + (yy - y)**2) / (2 * sigma**2))
    return np.clip(img + gaussian, 0, 1).astype(np.float32)


def random_pos_near_center(size, max_frac=0.25):
    """Random position within 25% of center (near galaxy)."""
    c = size // 2
    offset = int(size * max_frac)
    x = max(3, min(size - 4, c + random.randint(-offset, offset)))
    y = max(3, min(size - 4, c + random.randint(-offset, offset)))
    return x, y


def inject_artificial_sn(triplet):
    """Inject artificial SN into a triplet, return modified triplet.

    50% chance JWST SN (in both JWST, not HST)
    50% chance HST SN (in HST only)
    """
    hst, jwst1, jwst2 = triplet[0].copy(), triplet[1].copy(), triplet[2].copy()
    x, y = random_pos_near_center(IMAGE_SIZE)
    peak = random.uniform(0.15, 0.8)
    sigma = random.uniform(1.0, 3.0)

    if random.random() > 0.5:
        # JWST SN: in both JWST filters at same position
        jwst1 = inject_supernova_at(jwst1, x, y, peak, sigma)
        peak2 = peak * random.uniform(0.7, 1.3)
        jwst2 = inject_supernova_at(jwst2, x, y, peak2, sigma)
    else:
        # HST SN: in HST only
        hst = inject_supernova_at(hst, x, y, peak, sigma)

    return np.stack([hst, jwst1, jwst2], axis=0)


# ============================================================
# Datasets
# ============================================================

def augment_triplet(triplet):
    """Random flips and 90-degree rotation."""
    if random.random() > 0.5:
        triplet = np.flip(triplet, axis=2).copy()
    if random.random() > 0.5:
        triplet = np.flip(triplet, axis=1).copy()
    k = random.randint(0, 3)
    triplet = np.rot90(triplet, k, axes=(1, 2)).copy()
    return triplet


class VerifiedDataset(Dataset):
    """Dataset from verified ground truth (IDs 1-53131).

    7 real SN as positives, ~53K confirmed negatives.
    Positives are oversampled to appear more frequently.
    """

    def __init__(self, positive_files, negative_files,
                 oversample_pos=500, augment=True):
        # Each positive appears oversample_pos times
        self.positives = positive_files * oversample_pos
        self.negatives = negative_files
        self.all_samples = (
            [(f, 1.0) for f in self.positives] +
            [(f, 0.0) for f in self.negatives]
        )
        self.augment = augment
        print(f"  VerifiedDataset: {len(self.positives)} pos + "
              f"{len(self.negatives)} neg = {len(self.all_samples)} total")

    def __len__(self):
        return len(self.all_samples)

    def __getitem__(self, idx):
        files, label = self.all_samples[idx]
        triplet = load_triplet(files)
        if triplet is None:
            return torch.zeros(NUM_CHANNELS, IMAGE_SIZE, IMAGE_SIZE), torch.tensor(0.0)
        if self.augment:
            triplet = augment_triplet(triplet)
        return torch.tensor(triplet, dtype=torch.float32), torch.tensor(label, dtype=torch.float32)


class ArtificialSNDataset(Dataset):
    """Generate artificial SN by injecting into non-SN objects."""

    def __init__(self, non_sn_files, num_samples=5000, augment=True):
        self.non_sn_files = non_sn_files
        self.num_samples = num_samples
        self.augment = augment

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        files = random.choice(self.non_sn_files)
        triplet = load_triplet(files)
        if triplet is None:
            return torch.zeros(NUM_CHANNELS, IMAGE_SIZE, IMAGE_SIZE), torch.tensor(0.0)
        triplet = inject_artificial_sn(triplet)
        if self.augment:
            triplet = augment_triplet(triplet)
        return torch.tensor(triplet, dtype=torch.float32), torch.tensor(1.0, dtype=torch.float32)


# ============================================================
# CNN Model
# ============================================================

class SupernovaCNN(nn.Module):
    """3-channel CNN: HST + JWST1 + JWST2 -> P(supernova)."""

    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(NUM_CHANNELS, 16, 3, padding=1),
            nn.BatchNorm2d(16), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(16, 32, 3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(), nn.AdaptiveAvgPool2d(1),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(64, 1),
        )

    def forward(self, x):
        return self.classifier(self.features(x)).squeeze(1)


# ============================================================
# Training
# ============================================================

def train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * len(labels)
        preds = (torch.sigmoid(outputs) > 0.5).float()
        correct += (preds == labels).sum().item()
        total += len(labels)
    return total_loss / total, correct / total


def predict_batch(model, files_list, device, batch_size=256):
    """Predict probabilities for a list of file dicts."""
    model.eval()
    probs = []
    with torch.no_grad():
        for i in range(0, len(files_list), batch_size):
            batch_files = files_list[i:i+batch_size]
            tensors = []
            valid = []
            for files in batch_files:
                triplet = load_triplet(files)
                if triplet is not None:
                    tensors.append(torch.tensor(triplet, dtype=torch.float32))
                    valid.append(True)
                else:
                    tensors.append(torch.zeros(NUM_CHANNELS, IMAGE_SIZE, IMAGE_SIZE))
                    valid.append(False)
            batch = torch.stack(tensors).to(device)
            outputs = torch.sigmoid(model(batch)).cpu().numpy()
            for j, v in enumerate(valid):
                probs.append(float(outputs[j]) if v else 0.0)
    return probs


# ============================================================
# Main pipeline
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="Train CNN to detect supernovae."
    )
    parser.add_argument("--hst-dir",
        default="/data/astrofs2_1/suzuki/data/HST/cosmosacs/original_png/")
    parser.add_argument("--jwst-dir",
        default="/data/astrofs2_1/suzuki/data/JWST/cosmosweb/v0.8_png")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--num-artificial", type=int, default=5000)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--inference-workers", type=int, default=8)
    parser.add_argument("--inference-batch-size", type=int, default=256)
    parser.add_argument("--model-path", default="supernova_cnn.pth")
    parser.add_argument("--output-csv", default="supernova_cnn_candidates.csv")
    parser.add_argument(
        "--known-sn-csv", default=DEFAULT_KNOWN_SN_CSV,
        help=f"CSV of confirmed supernovae (default: {DEFAULT_KNOWN_SN_CSV})"
    )
    args = parser.parse_args()

    # Load ground-truth catalog and derive id sets
    known_sn = load_known_supernovae(args.known_sn_csv)
    known_sn_set = set(known_sn.keys())
    verified_sn_ids = {
        oid for oid in known_sn_set
        if oid.isdigit() and int(oid) <= VERIFIED_MAX_ID
    }
    print(f"Loaded {len(known_sn)} confirmed supernovae from {args.known_sn_csv}")
    print(f"  In verified range (ID <= {VERIFIED_MAX_ID}): {len(verified_sn_ids)}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # ==================================================================
    # STEP 1: Load and match files
    # ==================================================================
    print("\n" + "="*60)
    print("STEP 1: Loading and matching image files")
    print("="*60)

    file_map = build_file_maps(args.hst_dir, args.jwst_dir)
    paired = {k: v for k, v in file_map.items()
              if "hst" in v and "jwst1" in v and "jwst2" in v}
    print(f"Objects with all 3 images: {len(paired)}")

    known_sn_objects = {k: v for k, v in paired.items() if k in known_sn_set}
    print(f"Known SN found: {len(known_sn_objects)}/{len(known_sn_set)}")
    missing = known_sn_set - set(known_sn_objects.keys())
    if missing:
        print(f"  Missing: {sorted(missing)}")

    # ==================================================================
    # STEP 2: Build training data from verified ground truth
    # ==================================================================
    print("\n" + "="*60)
    print("STEP 2: Building training data")
    print("="*60)

    # Verified positives and negatives from ID range 1-53131
    verified_pos_files = []
    verified_neg_files = []
    for obj_id, files in paired.items():
        try:
            numeric_id = int(obj_id)
        except ValueError:
            continue
        if numeric_id <= VERIFIED_MAX_ID:
            if obj_id in verified_sn_ids:
                verified_pos_files.append(files)
            else:
                verified_neg_files.append(files)

    print(f"Verified range (ID 1-{VERIFIED_MAX_ID}):")
    print(f"  Real SN: {len(verified_pos_files)}")
    print(f"  Confirmed not SN: {len(verified_neg_files)}")

    # Add all known SN (across the full dataset) as additional positives
    for obj_id, files in known_sn_objects.items():
        if obj_id not in verified_sn_ids:
            verified_pos_files.append(files)
    print(f"  + {len(known_sn_objects) - len(verified_sn_ids)} additional known SN")
    print(f"  Total positives: {len(verified_pos_files)}")

    # Create datasets
    verified_dataset = VerifiedDataset(
        verified_pos_files, verified_neg_files,
        oversample_pos=500, augment=True)

    # Artificial SN for additional variety
    art_dataset = ArtificialSNDataset(
        verified_neg_files[:5000],
        num_samples=args.num_artificial, augment=True)
    print(f"Artificial SN samples: {args.num_artificial}")

    train_dataset = torch.utils.data.ConcatDataset([verified_dataset, art_dataset])
    train_loader = DataLoader(
        train_dataset, batch_size=args.batch_size, shuffle=True,
        num_workers=args.num_workers, pin_memory=True)
    print(f"Total training samples: {len(train_dataset)}")

    # ==================================================================
    # STEP 3: Train CNN
    # ==================================================================
    print("\n" + "="*60)
    print("STEP 3: Training CNN")
    print("="*60)

    model = SupernovaCNN().to(device)
    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=5, factor=0.5)

    best_recovery = 0
    best_epoch = 0

    # Prepare known SN files for validation
    known_files_list = [known_sn_objects[oid] for oid in sorted(known_sn_objects.keys())]
    known_ids_list = sorted(known_sn_objects.keys())

    for epoch in range(1, args.epochs + 1):
        train_loss, train_acc = train_epoch(
            model, train_loader, criterion, optimizer, device)

        # Check known SN recovery every 5 epochs
        if epoch % 5 == 0 or epoch == args.epochs or epoch == 1:
            probs = predict_batch(model, known_files_list, device)
            recovered = sum(1 for p in probs if p >= 0.5)

            # Show each known SN probability
            if epoch % 10 == 0 or epoch == args.epochs:
                for oid, p in zip(known_ids_list, probs):
                    tag = "OK" if p >= 0.5 else "MISS"
                    print(f"    {oid}: {p:.4f} [{tag}]")

            print(f"Epoch {epoch:3d}/{args.epochs} | "
                  f"loss: {train_loss:.4f} acc: {train_acc:.3f} | "
                  f"Known SN: {recovered}/{len(known_ids_list)}")

            if recovered >= best_recovery:
                best_recovery = recovered
                best_epoch = epoch
                torch.save(model.state_dict(), args.model_path)
            scheduler.step(train_loss)
        else:
            print(f"Epoch {epoch:3d}/{args.epochs} | "
                  f"loss: {train_loss:.4f} acc: {train_acc:.3f}")

    print(f"\nBest: {best_recovery}/{len(known_ids_list)} at epoch {best_epoch}")

    # ==================================================================
    # STEP 4: Validate — set threshold to recover all known SN
    # ==================================================================
    print("\n" + "="*60)
    print("STEP 4: Validating")
    print("="*60)

    model.load_state_dict(torch.load(args.model_path, weights_only=True))
    probs = predict_batch(model, known_files_list, device)

    print(f"\nKnown SN probabilities:")
    for oid, p in sorted(zip(known_ids_list, probs), key=lambda x: x[1], reverse=True):
        print(f"  {oid}: {p:.4f}")

    min_prob = min(probs)
    threshold = max(min_prob * 0.9, 0.01)
    print(f"\nLowest known SN prob: {min_prob:.4f}")
    print(f"Threshold: {threshold:.4f}")

    recovered = sum(1 for p in probs if p >= threshold)
    print(f"Recovery: {recovered}/{len(known_ids_list)}")

    # ==================================================================
    # STEP 5: Apply to all objects
    # ==================================================================
    print("\n" + "="*60)
    print(f"STEP 5: Applying to all {len(paired)} objects")
    print("="*60)

    all_probs_csv = args.output_csv.replace(".csv", "_all_probs.csv")

    class InferenceDataset(Dataset):
        def __init__(self, obj_ids, file_map):
            self.obj_ids = obj_ids
            self.file_map = file_map
        def __len__(self):
            return len(self.obj_ids)
        def __getitem__(self, idx):
            obj_id = self.obj_ids[idx]
            triplet = load_triplet(self.file_map[obj_id])
            if triplet is None:
                return obj_id, torch.zeros(NUM_CHANNELS, IMAGE_SIZE, IMAGE_SIZE), False
            return obj_id, torch.tensor(triplet, dtype=torch.float32), True

    def collate_fn(batch):
        ids = [b[0] for b in batch]
        tensors = torch.stack([b[1] for b in batch])
        valid = [b[2] for b in batch]
        return ids, tensors, valid

    obj_ids_sorted = sorted(paired.keys())
    inf_loader = DataLoader(
        InferenceDataset(obj_ids_sorted, paired),
        batch_size=args.inference_batch_size, shuffle=False,
        num_workers=args.inference_workers, pin_memory=True,
        collate_fn=collate_fn)

    start_time = time.time()
    num_candidates = 0
    completed = 0
    total = len(paired)

    csv_f = open(args.output_csv, "w", newline="")
    csv_w = csv.writer(csv_f)
    csv_w.writerow(["object_id", "probability", "known_sn"])

    all_f = open(all_probs_csv, "w", newline="")
    all_w = csv.writer(all_f)
    all_w.writerow(["object_id", "probability", "known_sn"])

    model.eval()
    try:
        with torch.no_grad():
            for batch_ids, batch_tensors, batch_valid in inf_loader:
                outputs = torch.sigmoid(
                    model(batch_tensors.to(device))).cpu().numpy()

                for i, obj_id in enumerate(batch_ids):
                    prob = float(outputs[i]) if batch_valid[i] else 0.0
                    is_known = "YES" if obj_id in known_sn_set else "NO"
                    all_w.writerow([obj_id, f"{prob:.6f}", is_known])

                    if prob >= threshold:
                        csv_w.writerow([obj_id, f"{prob:.4f}", is_known])
                        csv_f.flush()
                        num_candidates += 1
                        tag = "KNOWN" if is_known == "YES" else "NEW"
                        print(f"  *** SN CANDIDATE: {obj_id} "
                              f"(prob={prob:.4f}) [{tag}] ***")

                completed += len(batch_ids)
                if completed % 5000 < args.inference_batch_size or completed == total:
                    elapsed = time.time() - start_time
                    rate = completed / elapsed if elapsed > 0 else 0
                    eta = (total - completed) / rate if rate > 0 else 0
                    all_f.flush()
                    print(f"  Progress: {completed}/{total} "
                          f"({completed/total*100:.1f}%) "
                          f"| {rate:.0f} obj/s | ETA: {eta:.0f}s "
                          f"| Candidates: {num_candidates}")
    finally:
        csv_f.close()
        all_f.close()

    elapsed = time.time() - start_time
    print(f"\nDone in {elapsed:.1f}s")

    # ==================================================================
    # STEP 6: Final check
    # ==================================================================
    print("\n" + "="*60)
    print("STEP 6: Final verification")
    print("="*60)

    candidate_ids = set()
    with open(args.output_csv) as f:
        for row in csv.DictReader(f):
            candidate_ids.add(row["object_id"])

    known_in = set(known_sn_objects.keys())
    found = known_in & candidate_ids
    missed = known_in - candidate_ids
    rate = len(candidate_ids) / total * 1000 if total > 0 else 0

    print(f"Known SN recovered: {len(found)}/{len(known_in)}")
    for oid in sorted(found):
        print(f"  FOUND: {oid}")
    for oid in sorted(missed):
        print(f"  MISSED: {oid}")
    print(f"\nTotal candidates: {len(candidate_ids)}")
    print(f"Detection rate: {rate:.2f} per 1000")
    print(f"Threshold: {threshold:.4f}")
    print(f"\nFiles: {args.output_csv}, {all_probs_csv}")


if __name__ == "__main__":
    main()
